---
title: "Notes"
author: "Ben Welman"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cerulean
    highlight: kate
---

```{r setup, echo=FALSE}
suppressPackageStartupMessages(library(fpp3))
```

# Getting started

A time series is a sequence of observations collected at time intervals.

# Time series graphics

## tsibble objects

A time series object has a time component in it, called the **index**.

### The index variable {-}

**Yearly data**

```{r}
y <- tsibble(
	Year = 2015:2019,
	Observation = c(123, 39, 78, 52, 110),
	index = Year
)
y
```

**Quarterly data**

```{r}
x <- tibble(Quarter = seq(as.Date("2020-01-01"), as.Date("2020-12-31"), by = "1 quarter"),
			Observation = c(48, 73, 64, 120))
y <- x %>%
	mutate(Quarter = yearquarter(Quarter)) %>%
	as_tsibble(index = Quarter)
y
```

**Monthly data**

```{r}
x <- tibble(Month = seq(as.Date("2020-01-01"), as.Date("2020-12-31"), by = "1 month"),
			Observation = c(106, 58, 92, 33, 23, 70, 119, 41, 79, 29, 73, 58))
y <- x %>%
	mutate(Month = yearmonth(Month)) %>%
	as_tsibble(index = Month)
y
```

**Weekly data**

```{r}
x <- tibble(Week = seq(as.Date("2020-01-01"), as.Date("2020-06-30"), by = "1 week"),
			Observation = sample(100:500, size = 26))
y <- x %>%
	mutate(Week = yearweek(Week)) %>%
	as_tsibble(index = Week)
y
```

**Daily data**

```{r}
x <- tibble(Day = seq(as.Date("2020-01-01"), as.Date("2020-01-31"), by = "1 day"),
			Observation = sample(500:600, size = 31))
y <- x %>%
	as_tsibble(index = Day)
y
```

**ts data**

```{r}
x <- astsa::globtempl # a ts object
y <- as_tsibble(x)
y
```


# References

+ [Forecasting: Principles and Practice (3rd ed)](https://otexts.com/fpp3/)

+ [ETC3550Slides, Hyndman](https://github.com/robjhyndman/ETC3550Slides/tree/fable)
